### ISSUE TITLE
启动失败，很奇怪提示是没有python环境，但是我设置好了环境变量那些的。

### ISSUE THREAD

**Issue by klmyssn** [c0ny1/sqlmap4burp-plus-plus#5]
启动失败，很奇怪提示是没有python环境，但是我设置好了环境变量那些的，我单独再开个cmd同样的启动目录，python -V也是可以的
![图片](https://user-images.githubusercontent.com/37890522/78200400-26ff5800-74c1-11ea-8af1-b6924c0b2593.png)

**Comment by c0ny1** [comment]
首先确定下你设置的环境变量是针对当前用户的还是所有用户，最好设置为所有用户。

**Comment by c0ny1** [comment]
如果不是这个问题，有一个临时的解决方案，`python name`配置为`python.exe`的绝对路径。

**Comment by klmyssn** [comment]
谢谢师傅！我设置的所有用户的，然后我重启了下虚拟机就好了又~
